export const STATIONS = [
  { id: "LFS-001", code: "ALAUSA", name: "Alausa", defaultPassword: "ALAUSA@Fire24" },
  { id: "LFS-002", code: "IKEJA", name: "Ikeja", defaultPassword: "IKEJA@Fire24" },
  { id: "LFS-003", code: "IKORODU", name: "Ikorodu", defaultPassword: "IKORODU@Fire24" },
  { id: "LFS-004", code: "IMOTA", name: "Imota", defaultPassword: "IMOTA@Fire24" },
  { id: "LFS-005", code: "IJEDE", name: "Ijede", defaultPassword: "IJEDE@Fire24" },
  { id: "LFS-006", code: "ILUPEJU", name: "Ilupeju", defaultPassword: "ILUPEJU@Fire24" },
  { id: "LFS-007", code: "IJEGUN", name: "Ijegun-Egba", defaultPassword: "IJEGUN@Fire24" },
  { id: "LFS-008", code: "AGEGE", name: "Agege", defaultPassword: "AGEGE@Fire24" },
  { id: "LFS-009", code: "BOLADE", name: "Bolade", defaultPassword: "BOLADE@Fire24" },
  { id: "LFS-010", code: "BADAGRY", name: "Badagry", defaultPassword: "BADAGRY@Fire24" },
  { id: "LFS-011", code: "OJO", name: "Ojo", defaultPassword: "OJO@Fire24" },
  { id: "LFS-012", code: "EBUTE", name: "Ebute-Elefun", defaultPassword: "EBUTE@Fire24" },
  { id: "LFS-013", code: "ONIRU", name: "Oniru", defaultPassword: "ONIRU@Fire24" },
  { id: "LFS-014", code: "LEKKI2", name: "Lekki Phase 2", defaultPassword: "LEKKI2@Fire24" },
  { id: "LFS-015", code: "EPE1", name: "Epe 1", defaultPassword: "EPE1@Fire24" },
  { id: "LFS-016", code: "EPE2", name: "Epe 2", defaultPassword: "EPE2@Fire24" },
  { id: "LFS-017", code: "ABESAN", name: "Abesan", defaultPassword: "ABESAN@Fire24" },
  { id: "LFS-018", code: "EJIGBO", name: "Ejigbo", defaultPassword: "EJIGBO@Fire24" },
  { id: "LFS-019", code: "ISOLO", name: "Isolo", defaultPassword: "ISOLO@Fire24" },
  { id: "LFS-020", code: "AJEGUNLE", name: "Ajegunle", defaultPassword: "AJEGUNLE@Fire24" },
  { id: "LFS-021", code: "SARI", name: "Sari-Iganmu", defaultPassword: "SARI@Fire24" },
  { id: "LFS-022", code: "TOLU", name: "Tolu", defaultPassword: "TOLU@Fire24" },
  { id: "LFS-023", code: "SHOMOLU", name: "Shomolu", defaultPassword: "SHOMOLU@Fire24" },
  { id: "LFS-024", code: "OKOTA", name: "Okota", defaultPassword: "OKOTA@Fire24" }
];
